### ISSUE TITLE
Deploy Error on Github Pages

### ISSUE THREAD

**Issue by sergio-gn** [unoforge/agency-landing-page-Astrojs#5]
It worked like a charm on vercel, but I would like why on Github Pages it output this error?

YAML Exception reading /github/workspace/src/layouts/Layout.astro: (<unknown>): mapping values are not allowed in this context at line 6 column 8 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid YAML front matter in /github/workspace/src/pages/index.astro

**Comment by Johnkat-Mj** [comment]
Sorry for the delay, did you manage to solve this problem?
